[dependencies]
"php/php" = "=8.3.4"
"shyim/composer-wasmer" = "latest"

[fs]
"/app/" = "."

[[command]]
name = "run"
module = "shyim/composer-wasmer:sh"
runner = "wasi"
[command.annotations.wasi]
main-args = ["/app/start.sh"]
